### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by ashleyclough** [mapbox/spritezero-cli#5]
Am I doing something wrong? I get: 'npm ERR! 404 'spritezero-cli' is not in the npm registry' when running the command line installation.

**Comment by tmcw** [comment]
Waiting until https://github.com/mapbox/spritezero-cli/pull/4 is done to publish the first version so that we don't immediately need a major version bump

**Comment by tmcw** [comment]
https://github.com/mapbox/spritezero-cli/commit/1d311dca4728b4adeeb3dc2bdcef069fc2984464 - 1.0.1 is published.
