### ISSUE TITLE
Ignore .DS_Store

### ISSUE THREAD

**Issue by peterqliu** [mapbox/spritezero-cli#6]
EDIT: it looks like spritezero is trying to process this as an SVG.

Got this error when trying to spritify https://gist.github.com/peterqliu/7ff62635aa09fd1db79b, even though `width="72px" height="16px"` is explicitly in the markup. 

cc/ @tmcw @edenh

**Comment by peterqliu** [comment]
blocks https://github.com/mapbox/mapbox-gl-styles/pull/201

**Comment by mbretschn** [comment]
@peterqliu I had the same issue using OSX. I managed it to fix this by removing the .DS_Store file.

**Comment by peterqliu** [comment]
I realized that too! It looks like spritezero is trying to chew on that file, assuming it's an SVG.
